### PR TITLE
android: fix path in plugin.xml

### PR DESCRIPTION
**Pull request by stefdelec**

### CODE REVIEW

**Comment by abarisain** [comment]
Hello,

Thanks for trying to fix Ionic.

Won't that change break cordova? The manifest path is right for Cordova. If ionic moved it (or if ionic uses an outdated version of cordova), it is not something we want to support as we aim to be Cordova compatible first.

**Comment by stefdelec** [comment]
I have no idea. But you check other plugin.xml they seem to write path as I did in this PR.

**Comment by abarisain** [comment]
Sorry, but I'm not going to merge something that might break Cordova. The current path works fine, and I'm positive that others have used this version of the plugin with Ionic.

Please try using an older version of the plugin, such as 1.7.4

**Comment by abarisain** [comment]
If you really need this pr, I suggest you fork this repo and use your fork as a dependency

**Comment by jachstet-sea** [comment]
I'm experiencing problems with the plugin:
```
AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.batch.cordova.android.BatchCordovaPushReceiver: java.lang.IllegalArgumentException: No such service ComponentInfo{com.mycompany.myapp/com.batch.cordova.android.BatchCordovaPushService}
AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3978)
AndroidRuntime:        at android.app.ActivityThread.access$2300(ActivityThread.java:273)
AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2036)
AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:112)
AndroidRuntime:        at android.os.Looper.loop(Looper.java:216)
AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7593)
AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
AndroidRuntime: Caused by: java.lang.IllegalArgumentException: No such service ComponentInfo{com.mycompany.myapp/com.batch.cordova.android.BatchCordovaPushService}
AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:1957)
AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1921)
AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1871)
AndroidRuntime:        at android.app.job.IJobScheduler$Stub$Proxy.enqueue(IJobScheduler.java:215)
AndroidRuntime:        at android.app.JobSchedulerImpl.enqueue(JobSchedulerImpl.java:58)
AndroidRuntime:        at androidx.core.app.JobIntentService$JobWorkEnqueuer.enqueueWork(JobIntentService.java:342)
AndroidRuntime:        at androidx.core.app.JobIntentService.enqueueWork(JobIntentService.java:522)
AndroidRuntime:        at androidx.core.app.JobIntentService.enqueueWork(JobIntentService.java:500)
AndroidRuntime:        at com.batch.cordova.android.BatchCordovaPushService.enqueueWork(BatchCordovaPushService.java:37)
AndroidRuntime:        at com.batch.cordova.android.BatchCordovaPushReceiver.onReceive(BatchCordovaPushReceiver.java:18)
```

When I apply the fix here, it works without a problem.

Also, the official cordova-documentation doesn't have any path in their examples:
https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#config-file
https://cordova.apache.org/docs/en/3.0.0/plugin_ref/spec.html#config-file

So I wouldn't know why there should be a difference between "cordova"-Applications and "ionic"-Applications.

**Comment by abarisain** [comment]
Hi,

Ionic finds the config element fine, as it adds the broadcast receiver just fine (which is why the crash happens, the receiver expects that the service if there).
However, it seems to ignore the service for some unknown reason, even though they're both in the same config element. Meaning that Ionic picks up our change but only partially applies it.

A workaround we found is to add the batch plugin AFTER adding the android platform. If you add the plugin before the platform, the incorrect manifest is generated.

You can also make a custom pre build task that patches the manifest using a javascript hook.

The definitive solution is to bypass Ionic's broken manifest configuration by providing an AAR and letting Google's Gradle plugin merge the manifests.

**Comment by jachstet-sea** [comment]
Hm, adding the plugin after adding the platform would mean chaning our CI-build scripts ... I'd rather live with having our own fork of the plugin and use that instead.

Since we will be using our own fork anyways: Is it okay to update the SDK version used from 1.13.0 to 1.16.1 in `dist/src/android/batch.gradle`? Or will there be problems mixing the latest SDK with the current plugin's Java code?

> Regarding cordova not specifying any path in their example: if we don't do that, we run into other problems that result in the manifest not being properly modified either.

Could you please elaborate what kind of non-proper modifications there might be? Push notifications seem to be working. We didn't yet test the analytics/statistics since we are using the DEV keys for now.

Thank you!

**Comment by abarisain** [comment]
>adding the plugin after adding the platform would mean chaning our CI-build scripts

I understand that. It's the only workaround we've found so far.
This issue needs to be fixed upstream, but has been going on for years. I wouldn't hold my breath.

> Is it okay to update the SDK version used from 1.13.0 to 1.16.1

It should be.
Note that 1.16.1 requires androidx, so you might need to tweak the plugin's build.gradle to use androidx deps. You might also need to tweak your cordova project accordingly.
This is something that we will eventually update in the plugin too: androidx migration is inevitable.

>Could you please elaborate what kind of non-proper modifications there might be? 
By "not being properly modified", I mean not modified at all. Unfortunately your fix might work for you with a specific cordova-android version, but we handle a range of versions and Cordova's plugin API isn't exactly stable.

If the manifest isn't modified at all, handling of notifications when the app is in the foreground might be broken.
It's relatively easy to check if your manifest is merging properly: build the final apk, open it with jadx-gui and see if you see BatchCordovaPushReceiver and BatchCordovaPushService in the manifest.

**Comment by jachstet-sea** [comment]
Your reaction time is impressive :)

About AndroidX: Yes, our apps are already using it despite current cordova recommondation not to use it yet.

In our APK's Manifest (with the changes in this PR applied) I can see:
```
<service android:name="com.batch.cordova.android.BatchCordovaPushService" android:permission="android.permission.BIND_JOB_SERVICE"/>
<receiver android:name="com.batch.cordova.android.BatchCordovaPushReceiver" android:permission="com.google.android.c2dm.permission.SEND">
``` 

Push notifications that arrive while the app is in foreground are shown in the status bar + the phone vibrates. Is that the expected behaviour or should something happen in addition?

**Comment by abarisain** [comment]
All's good :)

**Pull request closed without merging**
